### ISSUE TITLE
Problem when using fetch

### ISSUE THREAD

**Issue by TradeFace** [reststate/reststate-client#12]
I use fetch for my vue-native project. When trying to integrate restate-vuex I didn't get any data back. I updated .then(extractData) with .then(extractData => extractData) in the client (v0.0.4) to get it working.

Thanks!

**Comment by CodingItWrong** [comment]
Thanks for reporting this; I definitely want the library to work in as many context as possible.

Could you provide a little more detail to help me follow the issue and change you're describing?

- When you say "I didn't get any data back" which specific getter is returning which value?
- Which line do you make the change to `.then(extractData => extractData)` on?
- Would it be possible for you to post the code for the component that's accessing this data? This could help me follow what's going on

**Comment by TradeFace** [comment]
I ended up editing line 15 `const extractData = response => response.data;` to `const extractData = response => response;`

Below my general purpose request function
```
request(method, url, data, success = null, error = null) {
        console.log(this.baseURL + url)
        var requestOptions = {
            method: method,
            headers: {
                "Content-Type": "application/json"
            }
        }

        if (data !== null) {
            requestOptions.body = JSON.stringify(data);
        }

        return fetch(this.baseURL + url, requestOptions)
           .then(success => success.json()).catch(error);
    },
```
Here you'll find the docs on implementation of fetch
[https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch](url)

HTH

**Comment by CodingItWrong** [comment]
Ah gotcha, I follow now—on the web I've always used Axios, but I'd like it to work with fetch as well. I see how the current implementation you pointed out is coupled to Axios' API. I'll look into this and try to make it as easy as possible to use with either. Thanks for the info!

**Comment by CodingItWrong** [comment]
Since you already have to write this custom function to use fetch, I think you could make a small adjustment to get it working. Try putting the returned json in the `data` attribute of a new object:

So change the code from:

```diff
.then(success => success.json())
```

to:

```diff
.then(success => ({ data: success.json() }))
```

**Comment by TradeFace** [comment]
Thanks for that solution. Much better than altering the lib!
