### ISSUE TITLE
Fetching relationships implementation

### ISSUE THREAD

**Issue by TradeFace** [reststate/reststate-client#13]
According to https://jsonapi.org/format/#fetching-relationships then patern to fetch a relationship is `/<primary>/<primary_id>/relationships/<secondary>` This implementation uses `/<primary>/<primary_id>/<secondary>`. That seems to be valid too. Could you make the relationships part of the request optional?

**Comment by TradeFace** [comment]
Misinterpretation from my side. 
`/<primary>/<primary_id>/relationships/<secondary>` should only return the id and type.
`/<primary>/<primary_id>/<secondary>` should return the data

**Comment by CodingItWrong** [comment]
Thanks for posting what you figured out, I wasn't aware of that distinction either 👍
